name: Terraform Deployment

on:
  push:
    branches:
      - main  # This ensures it triggers on the 'main' branch
  pull_request:
    branches:
      - main  # This ensures it triggers on pull requests to 'main' branch

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Using latest version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Using latest version
        with:
          terraform_version: 1.4.0

      - name: Format Check
        run: terraform fmt -check  # This checks Terraform code formatting

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Using latest version
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Using latest version
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Using latest version
        with:
          role-to-assume: arn:aws:iam::354918362336:role/GithubActionsRole  # Correct IAM Role ARN
          aws-region: eu-central-1  # Ensure this is the correct region

      - name: Terraform Init
        run: terraform init  # Initialize Terraform

      - name: Terraform Plan
        run: terraform plan  # Generate and output Terraform execution plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan  # This step runs after the terraform-plan job
    if: github.ref == 'refs/heads/main'  # Only apply if the branch is 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Using latest version

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Using latest version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # Using latest version
        with:
          role-to-assume: arn:aws:iam::354918362336:role/GithubActionsRole  # Correct IAM Role ARN
          aws-region: eu-central-1  # Ensure this is the correct region

      - name: Terraform Init
        run: terraform init  # Initialize Terraform for apply

      - name: Terraform Apply
        run: terraform apply -auto-approve  # Apply Terraform changes automatically
