name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Format Check
        run: terraform fmt -check  

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::354918362336:role/GithubActionsRole
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Add your correct working directory here if needed

      - name: Terraform Plan
        run: terraform plan -out=terraform.tfplan
        working-directory: ./terraform  # Same working directory

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::354918362336:role/GithubActionsRole
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Same working directory

      - name: Terraform Apply
        run: terraform apply -auto-approve terraform.tfplan
        working-directory: ./terraform  # Same working directory
